openapi: 3.0.0
info:
  title: Fruitables API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8000/api/v1
    description: Local Server
  - url: http://example.com
    description: Optional server description, e.g. Internal staging server for testing
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT    
security:
  - bearerAuth: []     
paths:
  /users/register:
    post:
      summary: User Registration
      description: Optional extended description in CommonMark or HTML.
      tags: 
      - users
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                role:
                  type: string
                email:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses: 
        '201':
          description: Created
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/login:
    post:
      summary: User Login
      description: Optional extended description in CommonMark or HTML.
      tags: 
      - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                email:
                  type: string
      responses: 
        '201':
          description: Created
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string                
  /users/logout:
     post:
      summary: User Logout
      description: Optional extended description in CommonMark or HTML.
      tags: 
      - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string                
  /users/newToken:
     post:
      summary: Generate a New Token.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string 
  /users/googleLogin:
    get:
        summary: Authenticate With Google.
        description: YOu Can Authenticate Direct With Browser.
        tags: 
        - users
        responses:
          '200':    # status code
            description: A JSON array of user names
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    type: string               
  /categories/list-categories:
      get:
        parameters:
          - in: query
            name: page
            schema:
              type: integer
            description: The number of items to skip before starting to collect the result set
          - in: query
            name: pageSize
            schema:
              type: integer
            description: The numbers of items to return
        summary: List the Categories
        description: Optional extended description in CommonMark or HTML.
        tags: 
        - categories
        responses:
          '200':    # status code
            description: A JSON array of user names
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    type: string  
  /categories/update-category/{category_id}:                                              
    put:
      summary: Update a Category
      description: Update the details of a specific category.
      tags:
      - categories
      parameters:
        - in: path
          name: category_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
        responses:
          '200':    # status code
            description: A JSON array of user names
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    type: string  
  /categories/delete-category/{category_id}:
    delete:
      summary: Delete a Category
      description: Remove a specific category from the list.
      tags:
        - categories
      parameters:
        - in: path
          name: category_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category successfully deleted.
        '404':
          description: Category not found.
                   
                  #  running into the browser like this for testing: http://localhost:8000/api-docs